### ISSUE TITLE
V1 Mixer startup "burp" 

### ISSUE THREAD

**Issue by ValleyAudio** [mschack/VCV-Rack-Plugins#87]
Hi,
I've found when using the 9_3_4 mixer, and potentially others, that on the outputs (either main or aux) a huge voltage spike or "burp" randomly occurs when a patch opens with these inserted. Possibly due to uninitialized variables?

**Comment by millxing** [comment]
This has happened to me also with the mixer.

**Comment by mschack** [comment]
Hi guys, sorry for the delay, almost forgot about this page... I have been working on this issue.  Seems to happen more on loading patches from VCV, though sometimes it happens when you start VCV up as well.  Hopefully I have a fix soon.  In the meantime you can bring the effect return back to a regular audio channel and it does not seem to happen.  Thanks!

**Comment by mschack** [comment]
out of interest, what OS are you guys using?

**Comment by millxing** [comment]
MacOS Mojave

**Comment by ValleyAudio** [comment]
I'm on Mojave too.

**Comment by espenstoro** [comment]
Late reply, but Windows 8.1 has had the same issue.

**Comment by mschack** [comment]
Yes there seems to be some sort of startup audio glitch that happens even without my mixer, but my AUX returns seems to cause an unbearable squeal...  I still don't understand what is going on with this but to smooth over the problem I now fade in my mixer slowly which seems to rid of the audio glitch and the squealing problem.

**Comment by mschack** [comment]
and my plugins are now released on VCV so you can upload the latest version through VCV Rack.

**Comment by millxing** [comment]
Thanks!
